//
//  Item.swift
//  Shiren6
//
//  Created by Shibata Toshiki on 2024/03/08.
//

import Foundation
import SwiftUI

struct Item: Hashable {
    let name: String
    let buyingPrive: Int
    let sellingPrice: Int
    let kind: Kind
}

enum Kind {
    case grass
    case scroll
    case pot
    case cane
    case bangle
    
    var image: Image {
        return Image(systemName: "square.and.arrow.up")
    }
}

enum Price {
    static let itemArray: [Item] = [
        // 草
        Item(name: "薬草", buyingPrive: 40, sellingPrice: 10, kind: .grass),
        Item(name: "毒草", buyingPrive: 50, sellingPrice: 20, kind: .grass),
        Item(name: "暴走の種", buyingPrive: 50, sellingPrice: 20, kind: .grass),
        Item(name: "混乱草", buyingPrive: 70, sellingPrice: 25, kind: .grass),
        Item(name: "睡眠草", buyingPrive: 70, sellingPrice: 25, kind: .grass),
        Item(name: "めつぶし", buyingPrive: 70, sellingPrice: 25, kind: .grass),
        Item(name: "すばやさ", buyingPrive: 70, sellingPrice: 25, kind: .grass),
        Item(name: "パワーアップ", buyingPrive: 70, sellingPrice: 25, kind: .grass),
        Item(name: "弟切草", buyingPrive: 80, sellingPrice: 30, kind: .grass),
        Item(name: "高飛び", buyingPrive: 100, sellingPrice: 40, kind: .grass),
        Item(name: "くねくね", buyingPrive: 100, sellingPrice: 40, kind: .grass),
        Item(name: "いやし", buyingPrive: 200, sellingPrice: 80, kind: .grass),
        Item(name: "かぐわし", buyingPrive: 200, sellingPrice: 80, kind: .grass),
        Item(name: "胃拡張", buyingPrive: 200, sellingPrice: 80, kind: .grass),
        Item(name: "胃縮小", buyingPrive: 200, sellingPrice: 80, kind: .grass),
        Item(name: "ドラゴン", buyingPrive: 250, sellingPrice: 100, kind: .grass),
        Item(name: "復活の草", buyingPrive: 400, sellingPrice: 160, kind: .grass),
        Item(name: "無敵草", buyingPrive: 400, sellingPrice: 160, kind: .grass),
        Item(name: "不幸の種", buyingPrive: 400, sellingPrice: 160, kind: .grass),
        Item(name: "命の草", buyingPrive: 500, sellingPrice: 200, kind: .grass),
        Item(name: "毒消し", buyingPrive: 600, sellingPrice: 240, kind: .grass),
        Item(name: "ちから", buyingPrive: 700, sellingPrice: 280, kind: .grass),
        Item(name: "しあわせの草", buyingPrive: 1000, sellingPrice: 400, kind: .grass),
        Item(name: "天使の種", buyingPrive: 2000, sellingPrice: 800, kind: .grass),
        Item(name: "超不幸", buyingPrive: 2000, sellingPrice: 800, kind: .grass),
        // 巻物
        Item(name: "混乱の巻物", buyingPrive: 300, sellingPrice: 120, kind: .scroll),
        Item(name: "バクスイの巻物", buyingPrive: 300, sellingPrice: 120, kind: .scroll),
        Item(name: "ゾワゾワの巻物", buyingPrive: 300, sellingPrice: 120, kind: .scroll),
        Item(name: "真空斬りの巻物", buyingPrive: 300, sellingPrice: 120, kind: .scroll),
        Item(name: "困ったときの巻物", buyingPrive: 300, sellingPrice: 120, kind: .scroll),
        Item(name: "銀封印の巻物", buyingPrive: 300, sellingPrice: 120, kind: .scroll),
        Item(name: "道具寄せの巻物", buyingPrive: 300, sellingPrice: 120, kind: .scroll),
        Item(name: "生物集合の巻物", buyingPrive: 300, sellingPrice: 120, kind: .scroll),
        Item(name: "識別の巻物", buyingPrive: 300, sellingPrice: 120, kind: .scroll),
        Item(name: "天の恵みの巻物", buyingPrive: 400, sellingPrice: 160, kind: .scroll),
        Item(name: "地の恵みの巻物", buyingPrive: 400, sellingPrice: 160, kind: .scroll),
        Item(name: "メッキの巻物", buyingPrive: 400, sellingPrice: 160, kind: .scroll),
        Item(name: "印増大の巻物", buyingPrive: 400, sellingPrice: 160, kind: .scroll),
        Item(name: "印消しの巻物", buyingPrive: 400, sellingPrice: 160, kind: .scroll),
        Item(name: "おにぎりの巻物", buyingPrive: 400, sellingPrice: 160, kind: .scroll),
        Item(name: "おはらいの巻物", buyingPrive: 600, sellingPrice: 240, kind: .scroll),
        Item(name: "あかりの巻物", buyingPrive: 600, sellingPrice: 240, kind: .scroll),
        Item(name: "迷子の巻物", buyingPrive: 600, sellingPrice: 240, kind: .scroll),
        Item(name: "罠消しの巻物", buyingPrive: 600, sellingPrice: 240, kind: .scroll),
        Item(name: "銀はがしの巻物", buyingPrive: 1000, sellingPrice: 400, kind: .scroll),
        Item(name: "壺増大の巻物", buyingPrive: 1000, sellingPrice: 400, kind: .scroll),
        Item(name: "吸出しの巻物", buyingPrive: 1000, sellingPrice: 400, kind: .scroll),
        Item(name: "呪いの巻物", buyingPrive: 1000, sellingPrice: 400, kind: .scroll),
        Item(name: "罠の巻物", buyingPrive: 1000, sellingPrice: 400, kind: .scroll),
        Item(name: "水がれの巻物", buyingPrive: 1000, sellingPrice: 400, kind: .scroll),
        Item(name: "大部屋の巻物", buyingPrive: 1000, sellingPrice: 400, kind: .scroll),
        Item(name: "魔物部屋の巻物", buyingPrive: 1000, sellingPrice: 400, kind: .scroll),
        Item(name: "バクチの巻物", buyingPrive: 1000, sellingPrice: 400, kind: .scroll),
        Item(name: "くちなしの巻物", buyingPrive: 1000, sellingPrice: 400, kind: .scroll),
        Item(name: "拾えずの巻物", buyingPrive: 1000, sellingPrice: 400, kind: .scroll),
        Item(name: "敵加速の巻物", buyingPrive: 1000, sellingPrice: 400, kind: .scroll),
        Item(name: "聖域の巻物", buyingPrive: 1000, sellingPrice: 400, kind: .scroll),
        Item(name: "全滅", buyingPrive: 3000, sellingPrice: 1200, kind: .scroll),
        Item(name: "ねだやし", buyingPrive: 10000, sellingPrice: 4000, kind: .scroll),
        // 腕輪
        Item(name: "遠投の腕輪", buyingPrive: 1500, sellingPrice: 600, kind: .bangle),
        Item(name: "ヘタ投げの腕輪", buyingPrive: 1500, sellingPrice: 600, kind: .bangle),
        Item(name: "連射の腕輪", buyingPrive: 1500, sellingPrice: 600, kind: .bangle),
        Item(name: "諸刃の腕輪", buyingPrive: 1500, sellingPrice: 600, kind: .bangle),
        Item(name: "痛恨の腕輪", buyingPrive: 1500, sellingPrice: 600, kind: .bangle),
        Item(name: "罠消しの腕輪", buyingPrive: 1500, sellingPrice: 600, kind: .bangle),
        Item(name: "垂れ流しの腕輪", buyingPrive: 1500, sellingPrice: 600, kind: .bangle),
        Item(name: "金垂れ流し", buyingPrive: 1500, sellingPrice: 600, kind: .bangle),
        Item(name: "ちからの腕輪", buyingPrive: 2000, sellingPrice: 800, kind: .bangle),
        Item(name: "気配察知の腕輪", buyingPrive: 2500, sellingPrice: 1000, kind: .bangle),
        Item(name: "道具感知の腕輪", buyingPrive: 2500, sellingPrice: 1000, kind: .bangle),
        Item(name: "睡眠よけの腕輪", buyingPrive: 2500, sellingPrice: 1000, kind: .bangle),
        Item(name: "大砲強化の腕輪", buyingPrive: 2500, sellingPrice: 1000, kind: .bangle),
        Item(name: "水グモの腕輪", buyingPrive: 3000, sellingPrice: 1200, kind: .bangle),
        Item(name: "呪いよけの腕輪", buyingPrive: 3000, sellingPrice: 1200, kind: .bangle),
        Item(name: "浮遊の腕輪", buyingPrive: 3000, sellingPrice: 1200, kind: .bangle),
        Item(name: "魔物呼びの腕輪", buyingPrive: 3000, sellingPrice: 1200, kind: .bangle),
        Item(name: "胃拡張の腕輪", buyingPrive: 3500, sellingPrice: 1400, kind: .bangle),
        Item(name: "胃縮小の腕輪", buyingPrive: 3500, sellingPrice: 1400, kind: .bangle),
        Item(name: "弾きよけの腕輪", buyingPrive: 3500, sellingPrice: 1400, kind: .bangle),
        Item(name: "値引切りの腕輪", buyingPrive: 3500, sellingPrice: 1400, kind: .bangle),
        Item(name: "しあわせの腕輪", buyingPrive: 4000, sellingPrice: 1600, kind: .bangle),
        Item(name: "混乱よけの腕輪", buyingPrive: 4000, sellingPrice: 1600, kind: .bangle),
        Item(name: "透視の腕輪", buyingPrive: 5000, sellingPrice: 2000, kind: .bangle),
        Item(name: "回復の腕輪", buyingPrive: 5000, sellingPrice: 2000, kind: .bangle),
        Item(name: "錆よけの腕輪", buyingPrive: 5000, sellingPrice: 2000, kind: .bangle),
        Item(name: "裏道の腕輪", buyingPrive: 5000, sellingPrice: 2000, kind: .bangle),
        Item(name: "すれ違いの腕輪", buyingPrive: 5000, sellingPrice: 2000, kind: .bangle),
        Item(name: "壁抜けの腕輪", buyingPrive: 6500, sellingPrice: 2600, kind: .bangle),
        Item(name: "忍び足の腕輪", buyingPrive: 6500, sellingPrice: 2600, kind: .bangle),
        Item(name: "毒消しの腕輪", buyingPrive: 6500, sellingPrice: 2600, kind: .bangle),
        Item(name: "罠師の腕輪", buyingPrive: 7500, sellingPrice: 3000, kind: .bangle),
        Item(name: "鑑定師の腕輪", buyingPrive: 7500, sellingPrice: 3000, kind: .bangle),
        Item(name: "百発百中の腕輪", buyingPrive: 15000, sellingPrice: 6000, kind: .bangle),
        
        // 壺
        Item(name: "保存の壺(0)", buyingPrive: 800, sellingPrice: 320, kind: .pot),
        Item(name: "保存の壺(1)", buyingPrive: 900, sellingPrice: 360, kind: .pot),
        Item(name: "保存の壺(2)", buyingPrive: 1000, sellingPrice: 400, kind: .pot),
        Item(name: "保存の壺(3)", buyingPrive: 1100, sellingPrice: 440, kind: .pot),
        Item(name: "保存の壺(4)", buyingPrive: 1200, sellingPrice: 480, kind: .pot),
        Item(name: "保存の壺(5)", buyingPrive: 1400, sellingPrice: 520, kind: .pot),

        Item(name: "ただの壺(0)", buyingPrive: 800, sellingPrice: 320, kind: .pot),
        Item(name: "ただの壺(1)", buyingPrive: 900, sellingPrice: 360, kind: .pot),
        Item(name: "ただの壺(2)", buyingPrive: 1000, sellingPrice: 400, kind: .pot),
        Item(name: "ただの壺(3)", buyingPrive: 1100, sellingPrice: 440, kind: .pot),
        Item(name: "ただの壺(4)", buyingPrive: 1200, sellingPrice: 480, kind: .pot),
        Item(name: "ただの壺(5)", buyingPrive: 1400, sellingPrice: 520, kind: .pot),
        
        Item(name: "識別の壺(0)", buyingPrive: 800, sellingPrice: 320, kind: .pot),
        Item(name: "識別の壺(1)", buyingPrive: 900, sellingPrice: 360, kind: .pot),
        Item(name: "識別の壺(2)", buyingPrive: 1000, sellingPrice: 400, kind: .pot),
        Item(name: "識別の壺(3)", buyingPrive: 1100, sellingPrice: 440, kind: .pot),
        Item(name: "識別の壺(4)", buyingPrive: 1200, sellingPrice: 480, kind: .pot),
        Item(name: "識別の壺(5)", buyingPrive: 1400, sellingPrice: 520, kind: .pot),

        Item(name: "変化の壺(0)", buyingPrive: 800, sellingPrice: 320, kind: .pot),
        Item(name: "変化の壺(1)", buyingPrive: 900, sellingPrice: 360, kind: .pot),
        Item(name: "変化の壺(2)", buyingPrive: 1000, sellingPrice: 400, kind: .pot),
        Item(name: "変化の壺(3)", buyingPrive: 1100, sellingPrice: 440, kind: .pot),
        Item(name: "変化の壺(4)", buyingPrive: 1200, sellingPrice: 480, kind: .pot),
        Item(name: "変化の壺(5)", buyingPrive: 1400, sellingPrice: 520, kind: .pot),
        
        Item(name: "やりすごしの壺(0)", buyingPrive: 800, sellingPrice: 320, kind: .pot),
        Item(name: "やりすごしの壺(1)", buyingPrive: 900, sellingPrice: 360, kind: .pot),
        Item(name: "やりすごしの壺(2)", buyingPrive: 1000, sellingPrice: 400, kind: .pot),
        Item(name: "やりすごしの壺(3)", buyingPrive: 1100, sellingPrice: 440, kind: .pot),
        Item(name: "やりすごしの壺(4)", buyingPrive: 1200, sellingPrice: 480, kind: .pot),
        Item(name: "やりすごしの壺(5)", buyingPrive: 1400, sellingPrice: 520, kind: .pot),
        
        
        Item(name: "手封じの壺(0)", buyingPrive: 1000, sellingPrice: 400, kind: .pot),
        Item(name: "手封じの壺(1)", buyingPrive: 1100, sellingPrice: 440, kind: .pot),
        Item(name: "手封じの壺(2)", buyingPrive: 1200, sellingPrice: 480, kind: .pot),
        Item(name: "手封じの壺(3)", buyingPrive: 1300, sellingPrice: 520, kind: .pot),
        Item(name: "手封じの壺(4)", buyingPrive: 1400, sellingPrice: 560, kind: .pot),
        Item(name: "手封じの壺(5)", buyingPrive: 1500, sellingPrice: 600, kind: .pot),
        
        
        Item(name: "割れないの壺(0)", buyingPrive: 1000, sellingPrice: 400, kind: .pot),
        Item(name: "割れないの壺(1)", buyingPrive: 1100, sellingPrice: 440, kind: .pot),
        Item(name: "割れないの壺(2)", buyingPrive: 1200, sellingPrice: 480, kind: .pot),
        Item(name: "割れないの壺(3)", buyingPrive: 1300, sellingPrice: 520, kind: .pot),
        Item(name: "割れないの壺(4)", buyingPrive: 1400, sellingPrice: 560, kind: .pot),
        Item(name: "割れないの壺(5)", buyingPrive: 1500, sellingPrice: 600, kind: .pot),
        
        Item(name: "換金の壺(0)", buyingPrive: 1000, sellingPrice: 400, kind: .pot),
        Item(name: "換金の壺(1)", buyingPrive: 1100, sellingPrice: 440, kind: .pot),
        Item(name: "換金の壺(2)", buyingPrive: 1200, sellingPrice: 480, kind: .pot),
        Item(name: "換金の壺(3)", buyingPrive: 1300, sellingPrice: 520, kind: .pot),
        Item(name: "換金の壺(4)", buyingPrive: 1400, sellingPrice: 560, kind: .pot),
        Item(name: "換金の壺(5)", buyingPrive: 1500, sellingPrice: 600, kind: .pot),
        
        Item(name: "底抜けの壺(0)", buyingPrive: 1000, sellingPrice: 400, kind: .pot),
        Item(name: "底抜けの壺(1)", buyingPrive: 1100, sellingPrice: 440, kind: .pot),
        Item(name: "底抜けの壺(2)", buyingPrive: 1200, sellingPrice: 480, kind: .pot),
        Item(name: "底抜けの壺(3)", buyingPrive: 1300, sellingPrice: 520, kind: .pot),
        Item(name: "底抜けの壺(4)", buyingPrive: 1400, sellingPrice: 560, kind: .pot),
        Item(name: "底抜けの壺(5)", buyingPrive: 1500, sellingPrice: 600, kind: .pot),
        
        Item(name: "倉庫の壺(0)", buyingPrive: 1000, sellingPrice: 400, kind: .pot),
        Item(name: "倉庫の壺(1)", buyingPrive: 1100, sellingPrice: 440, kind: .pot),
        Item(name: "倉庫の壺(2)", buyingPrive: 1200, sellingPrice: 480, kind: .pot),
        Item(name: "倉庫の壺(3)", buyingPrive: 1300, sellingPrice: 520, kind: .pot),
        Item(name: "倉庫の壺(4)", buyingPrive: 1400, sellingPrice: 560, kind: .pot),
        Item(name: "倉庫の壺(5)", buyingPrive: 1500, sellingPrice: 600, kind: .pot),
        
        Item(name: "おはらいの壺(0)", buyingPrive: 1600, sellingPrice: 640, kind: .pot),
        Item(name: "おはらいの壺(1)", buyingPrive: 1700, sellingPrice: 680, kind: .pot),
        Item(name: "おはらいの壺(2)", buyingPrive: 1800, sellingPrice: 720, kind: .pot),
        Item(name: "おはらいの壺(3)", buyingPrive: 1900, sellingPrice: 760, kind: .pot),
        Item(name: "おはらいの壺(4)", buyingPrive: 2000, sellingPrice: 800, kind: .pot),
        Item(name: "おはらいの壺(5)", buyingPrive: 2100, sellingPrice: 840, kind: .pot),
        
        Item(name: "呪いの壺(0)", buyingPrive: 1600, sellingPrice: 640, kind: .pot),
        Item(name: "呪いの壺(1)", buyingPrive: 1700, sellingPrice: 680, kind: .pot),
        Item(name: "呪いの壺(2)", buyingPrive: 1800, sellingPrice: 720, kind: .pot),
        Item(name: "呪いの壺(3)", buyingPrive: 1900, sellingPrice: 760, kind: .pot),
        Item(name: "呪いの壺(4)", buyingPrive: 2000, sellingPrice: 800, kind: .pot),
        Item(name: "呪いの壺(5)", buyingPrive: 2100, sellingPrice: 840, kind: .pot),
        
        Item(name: "背中の壺(0)", buyingPrive: 2000, sellingPrice: 800, kind: .pot),
        Item(name: "背中の壺(1)", buyingPrive: 2100, sellingPrice: 840, kind: .pot),
        Item(name: "背中の壺(2)", buyingPrive: 2200, sellingPrice: 880, kind: .pot),
        Item(name: "背中の壺(3)", buyingPrive: 2300, sellingPrice: 920, kind: .pot),
        Item(name: "背中の壺(4)", buyingPrive: 2400, sellingPrice: 960, kind: .pot),
        Item(name: "背中の壺(5)", buyingPrive: 2500, sellingPrice: 1000, kind: .pot),
        
        Item(name: "トドの壺(0)", buyingPrive: 2000, sellingPrice: 800, kind: .pot),
        Item(name: "トドの壺(1)", buyingPrive: 2100, sellingPrice: 840, kind: .pot),
        Item(name: "トドの壺(2)", buyingPrive: 2200, sellingPrice: 880, kind: .pot),
        Item(name: "トドの壺(3)", buyingPrive: 2300, sellingPrice: 920, kind: .pot),
        Item(name: "トドの壺(4)", buyingPrive: 2400, sellingPrice: 960, kind: .pot),
        Item(name: "トドの壺(5)", buyingPrive: 2500, sellingPrice: 1000, kind: .pot),
        
        Item(name: "水鉄砲の壺(0)", buyingPrive: 2000, sellingPrice: 800, kind: .pot),
        Item(name: "水鉄砲の壺(1)", buyingPrive: 2100, sellingPrice: 840, kind: .pot),
        Item(name: "水鉄砲の壺(2)", buyingPrive: 2200, sellingPrice: 880, kind: .pot),
        Item(name: "水鉄砲の壺(3)", buyingPrive: 2300, sellingPrice: 920, kind: .pot),
        Item(name: "水鉄砲の壺(4)", buyingPrive: 2400, sellingPrice: 960, kind: .pot),
        Item(name: "水鉄砲の壺(5)", buyingPrive: 2500, sellingPrice: 1000, kind: .pot),
        
        Item(name: "魔物の壺(0)", buyingPrive: 2000, sellingPrice: 800, kind: .pot),
        Item(name: "魔物の壺(1)", buyingPrive: 2100, sellingPrice: 840, kind: .pot),
        Item(name: "魔物の壺(2)", buyingPrive: 2200, sellingPrice: 880, kind: .pot),
        Item(name: "魔物の壺(3)", buyingPrive: 2300, sellingPrice: 920, kind: .pot),
        Item(name: "魔物の壺(4)", buyingPrive: 2400, sellingPrice: 960, kind: .pot),
        Item(name: "魔物の壺(5)", buyingPrive: 2500, sellingPrice: 1000, kind: .pot),
        
        Item(name: "笑いの壺(0)", buyingPrive: 2000, sellingPrice: 800, kind: .pot),
        Item(name: "笑いの壺(1)", buyingPrive: 2100, sellingPrice: 840, kind: .pot),
        Item(name: "笑いの壺(2)", buyingPrive: 2200, sellingPrice: 880, kind: .pot),
        Item(name: "笑いの壺(3)", buyingPrive: 2300, sellingPrice: 920, kind: .pot),
        Item(name: "笑いの壺(4)", buyingPrive: 2400, sellingPrice: 960, kind: .pot),
        Item(name: "笑いの壺(5)", buyingPrive: 2500, sellingPrice: 1000, kind: .pot),
        
        Item(name: "合成の壺(0)", buyingPrive: 6000, sellingPrice: 2400, kind: .pot),
        Item(name: "合成の壺(1)", buyingPrive: 6100, sellingPrice: 2440, kind: .pot),
        Item(name: "合成の壺(2)", buyingPrive: 6200, sellingPrice: 2480, kind: .pot),
        Item(name: "合成の壺(3)", buyingPrive: 6300, sellingPrice: 2520, kind: .pot),
        Item(name: "合成の壺(4)", buyingPrive: 6400, sellingPrice: 2560, kind: .pot),
        Item(name: "合成の壺(5)", buyingPrive: 6500, sellingPrice: 2600, kind: .pot),
        
        Item(name: "強化の壺(0)", buyingPrive: 10000, sellingPrice: 4000, kind: .pot),
        Item(name: "強化の壺(1)", buyingPrive: 10100, sellingPrice: 4040, kind: .pot),
        Item(name: "強化の壺(2)", buyingPrive: 10200, sellingPrice: 4080, kind: .pot),
        Item(name: "強化の壺(3)", buyingPrive: 10300, sellingPrice: 4120, kind: .pot),
        Item(name: "強化の壺(4)", buyingPrive: 10400, sellingPrice: 4160, kind: .pot),
        Item(name: "強化の壺(5)", buyingPrive: 10500, sellingPrice: 4200, kind: .pot),
        
        Item(name: "弱化の壺(0)", buyingPrive: 10000, sellingPrice: 4000, kind: .pot),
        Item(name: "弱化の壺(1)", buyingPrive: 10100, sellingPrice: 4040, kind: .pot),
        Item(name: "弱化の壺(2)", buyingPrive: 10200, sellingPrice: 4080, kind: .pot),
        Item(name: "弱化の壺(3)", buyingPrive: 10300, sellingPrice: 4120, kind: .pot),
        Item(name: "弱化の壺(4)", buyingPrive: 10400, sellingPrice: 4160, kind: .pot),
        Item(name: "弱化の壺(5)", buyingPrive: 10500, sellingPrice: 4200, kind: .pot),
        
        Item(name: "場所替えの杖(0)", buyingPrive: 500, sellingPrice: 200, kind: .cane),
        Item(name: "場所替えの杖(1)", buyingPrive: 600, sellingPrice: 240, kind: .cane),
        Item(name: "場所替えの杖(2)", buyingPrive: 700, sellingPrice: 280, kind: .cane),
        Item(name: "場所替えの杖(3)", buyingPrive: 800, sellingPrice: 320, kind: .cane),
        Item(name: "場所替えの杖(4)", buyingPrive: 900, sellingPrice: 360, kind: .cane),
        Item(name: "場所替えの杖(5)", buyingPrive: 1000, sellingPrice: 400, kind: .cane),
        Item(name: "場所替えの杖(6)", buyingPrive: 1100, sellingPrice: 440, kind: .cane),
        Item(name: "場所替えの杖(7)", buyingPrive: 1200, sellingPrice: 480, kind: .cane),
        
        Item(name: "吹き飛ばしの杖(0)", buyingPrive: 500, sellingPrice: 200, kind: .cane),
        Item(name: "吹き飛ばしの杖(1)", buyingPrive: 600, sellingPrice: 240, kind: .cane),
        Item(name: "吹き飛ばしの杖(2)", buyingPrive: 700, sellingPrice: 280, kind: .cane),
        Item(name: "吹き飛ばしの杖(3)", buyingPrive: 800, sellingPrice: 320, kind: .cane),
        Item(name: "吹き飛ばしの杖(4)", buyingPrive: 900, sellingPrice: 360, kind: .cane),
        Item(name: "吹き飛ばしの杖(5)", buyingPrive: 1000, sellingPrice: 400, kind: .cane),
        Item(name: "吹き飛ばしの杖(6)", buyingPrive: 1100, sellingPrice: 440, kind: .cane),
        Item(name: "吹き飛ばしの杖(7)", buyingPrive: 1200, sellingPrice: 480, kind: .cane),
        
        Item(name: "飛びつきの杖(0)", buyingPrive: 500, sellingPrice: 200, kind: .cane),
        Item(name: "飛びつきの杖(1)", buyingPrive: 600, sellingPrice: 240, kind: .cane),
        Item(name: "飛びつきの杖(2)", buyingPrive: 700, sellingPrice: 280, kind: .cane),
        Item(name: "飛びつきの杖(3)", buyingPrive: 800, sellingPrice: 320, kind: .cane),
        Item(name: "飛びつきの杖(4)", buyingPrive: 900, sellingPrice: 360, kind: .cane),
        Item(name: "飛びつきの杖(5)", buyingPrive: 1000, sellingPrice: 400, kind: .cane),
        Item(name: "飛びつきの杖(6)", buyingPrive: 1100, sellingPrice: 440, kind: .cane),
        Item(name: "飛びつきの杖(7)", buyingPrive: 1200, sellingPrice: 480, kind: .cane),
        
        Item(name: "転ばぬ先の杖(0)", buyingPrive: 500, sellingPrice: 200, kind: .cane),
        Item(name: "転ばぬ先の杖(1)", buyingPrive: 600, sellingPrice: 240, kind: .cane),
        Item(name: "転ばぬ先の杖(2)", buyingPrive: 700, sellingPrice: 280, kind: .cane),
        Item(name: "転ばぬ先の杖(3)", buyingPrive: 800, sellingPrice: 320, kind: .cane),
        Item(name: "転ばぬ先の杖(4)", buyingPrive: 900, sellingPrice: 360, kind: .cane),
        Item(name: "転ばぬ先の杖(5)", buyingPrive: 1000, sellingPrice: 400, kind: .cane),
        Item(name: "転ばぬ先の杖(6)", buyingPrive: 1100, sellingPrice: 440, kind: .cane),
        Item(name: "転ばぬ先の杖(7)", buyingPrive: 1200, sellingPrice: 480, kind: .cane),
        
        Item(name: "ただの杖(0)", buyingPrive: 500, sellingPrice: 200, kind: .cane),
        Item(name: "ただの杖(1)", buyingPrive: 600, sellingPrice: 240, kind: .cane),
        Item(name: "ただの杖(2)", buyingPrive: 700, sellingPrice: 280, kind: .cane),
        Item(name: "ただの杖(3)", buyingPrive: 800, sellingPrice: 320, kind: .cane),
        Item(name: "ただの杖(4)", buyingPrive: 900, sellingPrice: 360, kind: .cane),
        Item(name: "ただの杖(5)", buyingPrive: 1000, sellingPrice: 400, kind: .cane),
        Item(name: "ただの杖(6)", buyingPrive: 1100, sellingPrice: 440, kind: .cane),
        Item(name: "ただの杖(7)", buyingPrive: 1200, sellingPrice: 480, kind: .cane),
        
        
        Item(name: "かなしばりの杖(0)", buyingPrive: 500, sellingPrice: 200, kind: .cane),
        Item(name: "かなしばりの杖(1)", buyingPrive: 600, sellingPrice: 240, kind: .cane),
        Item(name: "かなしばりの杖(2)", buyingPrive: 700, sellingPrice: 280, kind: .cane),
        Item(name: "かなしばりの杖(3)", buyingPrive: 800, sellingPrice: 320, kind: .cane),
        Item(name: "かなしばりの杖(4)", buyingPrive: 900, sellingPrice: 360, kind: .cane),
        Item(name: "かなしばりの杖(5)", buyingPrive: 1000, sellingPrice: 400, kind: .cane),
        Item(name: "かなしばりの杖(6)", buyingPrive: 1100, sellingPrice: 440, kind: .cane),
        Item(name: "かなしばりの杖(7)", buyingPrive: 1200, sellingPrice: 480, kind: .cane),
        
        Item(name: "封印の杖(0)", buyingPrive: 500, sellingPrice: 200, kind: .cane),
        Item(name: "封印の杖(1)", buyingPrive: 600, sellingPrice: 240, kind: .cane),
        Item(name: "封印の杖(2)", buyingPrive: 700, sellingPrice: 280, kind: .cane),
        Item(name: "封印の杖(3)", buyingPrive: 800, sellingPrice: 320, kind: .cane),
        Item(name: "封印の杖(4)", buyingPrive: 900, sellingPrice: 360, kind: .cane),
        Item(name: "封印の杖(5)", buyingPrive: 1000, sellingPrice: 400, kind: .cane),
        Item(name: "封印の杖(6)", buyingPrive: 1100, sellingPrice: 440, kind: .cane),
        Item(name: "封印の杖(7)", buyingPrive: 1200, sellingPrice: 480, kind: .cane),
        
        Item(name: "感電の杖(0)", buyingPrive: 500, sellingPrice: 200, kind: .cane),
        Item(name: "感電の杖(1)", buyingPrive: 600, sellingPrice: 240, kind: .cane),
        Item(name: "感電の杖(2)", buyingPrive: 700, sellingPrice: 280, kind: .cane),
        Item(name: "感電の杖(3)", buyingPrive: 800, sellingPrice: 320, kind: .cane),
        Item(name: "感電の杖(4)", buyingPrive: 900, sellingPrice: 360, kind: .cane),
        Item(name: "感電の杖(5)", buyingPrive: 1000, sellingPrice: 400, kind: .cane),
        Item(name: "感電の杖(6)", buyingPrive: 1100, sellingPrice: 440, kind: .cane),
        Item(name: "感電の杖(7)", buyingPrive: 1200, sellingPrice: 480, kind: .cane),
        
        Item(name: "トンネルの杖(0)", buyingPrive: 700, sellingPrice: 280, kind: .cane),
        Item(name: "トンネルの杖(1)", buyingPrive: 800, sellingPrice: 320, kind: .cane),
        Item(name: "トンネルの杖(2)", buyingPrive: 900, sellingPrice: 360, kind: .cane),
        Item(name: "トンネルの杖(3)", buyingPrive: 1000, sellingPrice: 320, kind: .cane),
        Item(name: "トンネルの杖(4)", buyingPrive: 1100, sellingPrice: 360, kind: .cane),
        Item(name: "トンネルの杖(5)", buyingPrive: 1200, sellingPrice: 400, kind: .cane),
        Item(name: "トンネルの杖(6)", buyingPrive: 1300, sellingPrice: 440, kind: .cane),
        Item(name: "トンネルの杖(7)", buyingPrive: 1400, sellingPrice: 480, kind: .cane),
        
        Item(name: "土塊の杖(0)", buyingPrive: 700, sellingPrice: 280, kind: .cane),
        Item(name: "土塊の杖(1)", buyingPrive: 800, sellingPrice: 320, kind: .cane),
        Item(name: "土塊の杖(2)", buyingPrive: 900, sellingPrice: 360, kind: .cane),
        Item(name: "土塊の杖(3)", buyingPrive: 1000, sellingPrice: 320, kind: .cane),
        Item(name: "土塊の杖(4)", buyingPrive: 1100, sellingPrice: 360, kind: .cane),
        Item(name: "土塊の杖(5)", buyingPrive: 1200, sellingPrice: 400, kind: .cane),
        Item(name: "土塊の杖(6)", buyingPrive: 1300, sellingPrice: 440, kind: .cane),
        Item(name: "土塊の杖(7)", buyingPrive: 1400, sellingPrice: 480, kind: .cane),
        
        Item(name: "鈍足の杖(0)", buyingPrive: 700, sellingPrice: 280, kind: .cane),
        Item(name: "鈍足の杖(1)", buyingPrive: 800, sellingPrice: 320, kind: .cane),
        Item(name: "鈍足の杖(2)", buyingPrive: 900, sellingPrice: 360, kind: .cane),
        Item(name: "鈍足の杖(3)", buyingPrive: 1000, sellingPrice: 320, kind: .cane),
        Item(name: "鈍足の杖(4)", buyingPrive: 1100, sellingPrice: 360, kind: .cane),
        Item(name: "鈍足の杖(5)", buyingPrive: 1200, sellingPrice: 400, kind: .cane),
        Item(name: "鈍足の杖(6)", buyingPrive: 1300, sellingPrice: 440, kind: .cane),
        Item(name: "鈍足の杖(7)", buyingPrive: 1400, sellingPrice: 480, kind: .cane),
        
        Item(name: "加速の杖(0)", buyingPrive: 700, sellingPrice: 280, kind: .cane),
        Item(name: "加速の杖(1)", buyingPrive: 800, sellingPrice: 320, kind: .cane),
        Item(name: "加速の杖(2)", buyingPrive: 900, sellingPrice: 360, kind: .cane),
        Item(name: "加速の杖(3)", buyingPrive: 1000, sellingPrice: 320, kind: .cane),
        Item(name: "加速の杖(4)", buyingPrive: 1100, sellingPrice: 360, kind: .cane),
        Item(name: "加速の杖(5)", buyingPrive: 1200, sellingPrice: 400, kind: .cane),
        Item(name: "加速の杖(6)", buyingPrive: 1300, sellingPrice: 440, kind: .cane),
        Item(name: "加速の杖(7)", buyingPrive: 1400, sellingPrice: 480, kind: .cane),
        
        Item(name: "導きの杖(0)", buyingPrive: 700, sellingPrice: 280, kind: .cane),
        Item(name: "導きの杖(1)", buyingPrive: 800, sellingPrice: 320, kind: .cane),
        Item(name: "導きの杖(2)", buyingPrive: 900, sellingPrice: 360, kind: .cane),
        Item(name: "導きの杖(3)", buyingPrive: 1000, sellingPrice: 320, kind: .cane),
        Item(name: "導きの杖(4)", buyingPrive: 1100, sellingPrice: 360, kind: .cane),
        Item(name: "導きの杖(5)", buyingPrive: 1200, sellingPrice: 400, kind: .cane),
        Item(name: "導きの杖(6)", buyingPrive: 1300, sellingPrice: 440, kind: .cane),
        Item(name: "導きの杖(7)", buyingPrive: 1400, sellingPrice: 480, kind: .cane),
        
        Item(name: "魔導の杖(0)", buyingPrive: 1000, sellingPrice: 400, kind: .cane),
        Item(name: "魔導の杖(1)", buyingPrive: 1100, sellingPrice: 440, kind: .cane),
        Item(name: "魔導の杖(2)", buyingPrive: 1200, sellingPrice: 480, kind: .cane),
        Item(name: "魔導の杖(3)", buyingPrive: 1300, sellingPrice: 520, kind: .cane),
        Item(name: "魔導の杖(4)", buyingPrive: 1400, sellingPrice: 560, kind: .cane),
        Item(name: "魔導の杖(5)", buyingPrive: 1500, sellingPrice: 600, kind: .cane),
        Item(name: "魔導の杖(6)", buyingPrive: 1600, sellingPrice: 640, kind: .cane),
        Item(name: "魔導の杖(7)", buyingPrive: 1700, sellingPrice: 680, kind: .cane),
        
        Item(name: "痛み分けの杖(0)", buyingPrive: 1000, sellingPrice: 400, kind: .cane),
        Item(name: "痛み分けの杖(1)", buyingPrive: 1100, sellingPrice: 440, kind: .cane),
        Item(name: "痛み分けの杖(2)", buyingPrive: 1200, sellingPrice: 480, kind: .cane),
        Item(name: "痛み分けの杖(3)", buyingPrive: 1300, sellingPrice: 520, kind: .cane),
        Item(name: "痛み分けの杖(4)", buyingPrive: 1400, sellingPrice: 560, kind: .cane),
        Item(name: "痛み分けの杖(5)", buyingPrive: 1500, sellingPrice: 600, kind: .cane),
        Item(name: "痛み分けの杖(6)", buyingPrive: 1600, sellingPrice: 640, kind: .cane),
        Item(name: "痛み分けの杖(7)", buyingPrive: 1700, sellingPrice: 680, kind: .cane),
        
        Item(name: "一時しのぎの杖(0)", buyingPrive: 1000, sellingPrice: 400, kind: .cane),
        Item(name: "一時しのぎの杖(1)", buyingPrive: 1100, sellingPrice: 440, kind: .cane),
        Item(name: "一時しのぎの杖(2)", buyingPrive: 1200, sellingPrice: 480, kind: .cane),
        Item(name: "一時しのぎの杖(3)", buyingPrive: 1300, sellingPrice: 520, kind: .cane),
        Item(name: "一時しのぎの杖(4)", buyingPrive: 1400, sellingPrice: 560, kind: .cane),
        Item(name: "一時しのぎの杖(5)", buyingPrive: 1500, sellingPrice: 600, kind: .cane),
        Item(name: "一時しのぎの杖(6)", buyingPrive: 1600, sellingPrice: 640, kind: .cane),
        Item(name: "一時しのぎの杖(7)", buyingPrive: 1700, sellingPrice: 680, kind: .cane),
        
        Item(name: "幸せの杖(0)", buyingPrive: 1000, sellingPrice: 400, kind: .cane),
        Item(name: "幸せの杖(1)", buyingPrive: 1100, sellingPrice: 440, kind: .cane),
        Item(name: "幸せの杖(2)", buyingPrive: 1200, sellingPrice: 480, kind: .cane),
        Item(name: "幸せの杖(3)", buyingPrive: 1300, sellingPrice: 520, kind: .cane),
        Item(name: "幸せの杖(4)", buyingPrive: 1400, sellingPrice: 560, kind: .cane),
        Item(name: "幸せの杖(5)", buyingPrive: 1500, sellingPrice: 600, kind: .cane),
        Item(name: "幸せの杖(6)", buyingPrive: 1600, sellingPrice: 640, kind: .cane),
        Item(name: "幸せの杖(7)", buyingPrive: 1700, sellingPrice: 680, kind: .cane),
        
        Item(name: "不幸の杖(0)", buyingPrive: 1000, sellingPrice: 400, kind: .cane),
        Item(name: "不幸の杖(1)", buyingPrive: 1100, sellingPrice: 440, kind: .cane),
        Item(name: "不幸の杖(2)", buyingPrive: 1200, sellingPrice: 480, kind: .cane),
        Item(name: "不幸の杖(3)", buyingPrive: 1300, sellingPrice: 520, kind: .cane),
        Item(name: "不幸の杖(4)", buyingPrive: 1400, sellingPrice: 560, kind: .cane),
        Item(name: "不幸の杖(5)", buyingPrive: 1500, sellingPrice: 600, kind: .cane),
        Item(name: "不幸の杖(6)", buyingPrive: 1600, sellingPrice: 640, kind: .cane),
        Item(name: "不幸の杖(7)", buyingPrive: 1700, sellingPrice: 680, kind: .cane),
        
        Item(name: "身代わりの杖(0)", buyingPrive: 2000, sellingPrice: 800, kind: .cane),
        Item(name: "身代わりの杖(1)", buyingPrive: 2100, sellingPrice: 840, kind: .cane),
        Item(name: "身代わりの杖(2)", buyingPrive: 2200, sellingPrice: 880, kind: .cane),
        Item(name: "身代わりの杖(3)", buyingPrive: 2300, sellingPrice: 920, kind: .cane),
        Item(name: "身代わりの杖(4)", buyingPrive: 2400, sellingPrice: 960, kind: .cane),
        Item(name: "身代わりの杖(5)", buyingPrive: 2500, sellingPrice: 1000, kind: .cane),
        Item(name: "身代わりの杖(6)", buyingPrive: 2600, sellingPrice: 1040, kind: .cane),
        Item(name: "身代わりの杖(7)", buyingPrive: 2700, sellingPrice: 1080, kind: .cane),
        
        Item(name: "桃まんの杖(0)", buyingPrive: 2000, sellingPrice: 800, kind: .cane),
        Item(name: "桃まんの杖(1)", buyingPrive: 2100, sellingPrice: 840, kind: .cane),
        Item(name: "桃まんの杖(2)", buyingPrive: 2200, sellingPrice: 880, kind: .cane),
        Item(name: "桃まんの杖(3)", buyingPrive: 2300, sellingPrice: 920, kind: .cane),
        Item(name: "桃まんの杖(4)", buyingPrive: 2400, sellingPrice: 960, kind: .cane),
        Item(name: "桃まんの杖(5)", buyingPrive: 2500, sellingPrice: 1000, kind: .cane),
        Item(name: "桃まんの杖(6)", buyingPrive: 2600, sellingPrice: 1040, kind: .cane),
        Item(name: "桃まんの杖(7)", buyingPrive: 2700, sellingPrice: 1080, kind: .cane),
        
        
    ]
}
